require "impatient"
require "njan.options"
require "njan.keymaps"
require "njan.plugins"
require "njan.nvim-colorizer"
--[[ require "njan.vscode" ]]
--[[ require "njan.tokyonight" ]]
require "njan.colorscheme"
require "njan.lualine"
require "njan.illuminate"
require "njan.cmp"
require "njan.lsp"
require "njan.telescope"
require "njan.treesitter"
require "njan.autopairs"
require "njan.comments"
require "njan.gitsigns"
require "njan.nvim-tree"
--[[ require "njan.bufferline" ]]
require "njan.toggleterm"
require "njan.nvim-which-key"
require "njan.flutter-tools"
require "njan.barbecue"
require "njan.nvim-neoscroll"
require "njan.surround"
require "njan.alpha"
require "njan.nvim-indent-blankline"
